kind: Service
apiVersion: v1
metadata:
  name: springboot-postgres-k8s
#  namespace: book-store-ns
  labels:
    app: springboot-postgres-k8s
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot-postgres-k8s
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-postgres-k8s
#  namespace: book-store-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-postgres-k8s
  template:
    metadata:
      labels:
        app: springboot-postgres-k8s
    spec:
      containers:
        - name: springboot-postgres-k8s
          image: ristovvski/devopsbookproject:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
